name: Publicar NuGet

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Restaurar paquetes NuGet
        run: dotnet restore

      - name: Compilar proyecto
        run: dotnet build -c Release

      - name: Verificar archivo DLL
        run: ls ./er.library.mq/bin/Release/net8.0

      - name: Crear paquete NuGet
        run: dotnet pack -c Release --no-build

      - name: Listar archivos del paquete NuGet
        run: ls ./er.library.mq/bin/Release

      - name: Inspeccionar contenido del paquete NuGet
        run: unzip -l ./er.library.mq/bin/Release/*.nupkg

      - name: Publicar paquete NuGet
        run: dotnet nuget push ./er.library.mq/bin/Release/*.nupkg --source "https://nuget.pkg.github.com/Energia-Real/index.json" --api-key ${{ secrets.IMPLEMENT_NUGET_TOKEN }}
